import 'package:animation_wrappers/animations/faded_scale_animation.dart';
import 'package:auto_route/annotations.dart';
import 'package:auto_route/auto_route.dart';
import 'package:blog_app/core/constants/my_assets.dart';
import 'package:blog_app/core/constants/my_colors.dart';
import 'package:blog_app/utils/utils.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
part 'splash.dart';